Bootable JAR 3.0 announcement
wildfly/wildfly.org pull request #228
Opened 2021-01-14 18:35 UTC by jfdenise

@bstansberry @jamezp , This the Bootable JAR 3.0 announcement. The date has been set to tomorrow (15th of january).
Thank-you.

2021-01-14 21:11 UTC, bstansberry requested changes
@jfdenise This looks fine. I have some minor, optional suggestions. I'll be sure to merge this tomorrow.

2021-01-14 21:11 UTC, bstansberry commented on _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
> +this link:https://www.wildfly.org/news/2020/10/19/bootable-jar-2.0-released/[blog post] that covers it in details.
s/details/detail

2021-01-14 21:11 UTC, bstansberry commented on _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
> +an OIDC client adapter by the mean of a Galleon layer.
s/mean/means

2021-01-14 21:11 UTC, bstansberry commented on _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
> +Keycloak Galleon feature-pack is not registered inside an universe, you need to specify its Maven coordinates.
s/Keycloak/Since the Keycloak/g

2021-01-14 21:11 UTC, bstansberry commented on _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
> +When building a Bootable JAR, the plugin retrieves the feature-packs from Maven repositories and provision a server based on the set of Galleon layers.
s/provision/provisions

2021-01-14 21:11 UTC, bstansberry commented on _posts/2021-01-15-bootable-jar-3.0.Final-Released.adoc
> +You have an interesting use-case, simple enough to be reduced to a simple example, and it is not covered
s/You/If you/g

2021-01-15 11:05 UTC, jfdenise commented
@bstansberry , thank-you. I fixed your findings, we have released a 3.0.2 to address an issue on Windows, I have updated the doc to rely on this version. In addition I have added a small chapter to introduce the work that is being done with ODO+dev-watch on Openshift.

2021-01-15 14:46 UTC, merged

2021-01-15 14:46 UTC, bstansberry commented
Thanks @jfdenise