Configure a Bootable Jar cluster application to use DNS_PING protocol
wildfly/wildfly.org pull request #241
Opened 2021-03-10 13:42 UTC by yersan

A blog post about of how to configure DNS ping protocol for a Bootable Jar cluster application

2021-03-10 13:57 UTC, jmesnil reviewed
That's a great introduction to bootable jar script to specialise an application

2021-03-10 16:08 UTC, yersan commented on _posts/2021-03-15-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +We recently described in this https://www.wildfly.org/news/2021/02/01/Bootable-jar-jkube-clustering-openshift[post] details about how to deploy and configure a WildFly Bootable JAR cluster applicatio
Much better, thanks for the suggestion. Done.

2021-03-10 16:09 UTC, yersan commented on _posts/2021-03-15-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +In this guide we will explain how you can configure the same Bootable JAR cluster application but this time by using http://www.jgroups.org/manual5/#_dns_ping[DNS_PING] protocol.
Fixed.

2021-03-10 16:09 UTC, yersan commented on _posts/2021-03-15-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +[NOTE]
Yes, I agree. I moved it to the beginning and added a note about the follow-up on the previous article.

2021-03-10 16:09 UTC, yersan commented on _posts/2021-03-15-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +1. If you have already cloned the demo application, checkout the *dns_ping* branch.
I added how to clone it and avoid assume it is already clone.

2021-03-10 16:10 UTC, yersan reviewed
Thank you @jmesnil for the review, I followed up on all your suggestions

2021-03-11 02:37 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +date:   2021-03-10
Can you change this date and the file name to 2021-03-12 please?

The WF 23 release announcement will go out tomorrow and I want it to be the first post on the list that day. But I don't want this getting buried under it either; it's really good and I want it on top. Merging it Friday will achieve that.

2021-03-11 02:51 UTC, bstansberry requested changes
Very nice content!

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +This post is a continuation of https://www.wildfly.org/news/2021/02/01/Bootable-jar-jkube-clustering-openshift[WildFly Bootable JAR cluster application with JKube openshift-maven-plugin] blog post, i
s/continuation of/continuation of my/g

s/post, it/post. It/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +We recently described in this https://www.wildfly.org/news/2021/02/01/Bootable-jar-jkube-clustering-openshift[post] details about how to deploy and configure a WildFly Bootable JAR cluster applicatio
s/for clustering discovery/for its clustering discovery/g

s/could not/may not/g

s/scenario, for example/scenario; for example/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +In this guide we will explain how you can configure the same Bootable JAR cluster application but this time by using the http://www.jgroups.org/manual5/#_dns_ping[DNS_PING] protocol.
s/time by using/time using/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +To sum up, we will need a Kubernetes service with a matching label selector to define which pods will be part of our cluster, and we will tell to the JGroups subsystem that we want to use such a serv
s/tell to the/tell the/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +The ping service is just an additional Kubernetes service resource. We are using https://www.eclipse.org/jkube/docs/openshift-maven-plugin[JKube openshift-maven-plugin] to deploy our application, thi
s/are using/are using the/g

s/application, this/application. This/g

s/is to create/is create/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +We have also configured the service with *publishNotReadyAddresses: true*. This configuration specifies that when there is a DNS lookup by using this service, the result will contain all pods matchin
s/need it to/need this in order to/g

Perhaps add "We want the JGroups cluster to form before the pods are receiving end user requests."

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +We have also added *clusterIP: None* in the service spec, it means this service will not assign a cluster IP through which clients can connect to the all pods backing it, instead it will return an IP
s/spec, it/spec. This/g

s/to the all/to all the/g

s/it, instead/it; instead/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +The script removes the existing *kubernetes.KUBE_PING* protocol and adds the *dns.DNS_PING*. The value of the *dns_query* property will be retrieved from an environment variable named *DNS_PING_SERVI
s/section on the/section of the/g

2021-03-11 02:51 UTC, bstansberry commented on _posts/2021-03-10-Bootable-jar-jkube-clustering-dns-ping-openshift.adoc
> +The maven _openshift_ profile looks like as https://github.com/yersan/wildfly-clustering-demo/blob/dns-ping/pom.xml#L53-L100[follows]:
s/like as/as

2021-03-11 10:44 UTC, yersan reviewed
Thank you @jmesnil and @bstansberry for the additional review and feedback, I followed your suggestions and added a minimal conclusion paragraph at the end.

2021-03-12 16:03 UTC, merged