Add post about WildFly Docker and new provisioning architecture
wildfly/wildfly.org pull request #349
Opened 2022-08-02 14:15 UTC by jmesnil

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

2022-08-02 20:12 UTC, bstansberry requested changes
General content looks good; I've just made some copy-editing notes.

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +title: 'Use the wildfly-maven-plugin to create Docker image of your application'
s/create/create a/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +In this article, we will explain how a developer using the Docker image for WildFly can take advantage of the new capabilities of the `wildlfy-maven-plugin` and the new WildFy runtime image to build
s/WildFy/WildFly

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +While S2I is a good technology to build application image on OpenShift, we realized that we could achieve a more flexible solution that would benefit other container platforms (Kubernetes, Azure) as
s/image/images or s/application/an application/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +We decided to focus on a Maven-centric approach to provision WildFly so that Maven (and the user) would be in control of the complete runtime (including the user deployment as well as WildFly runtime
s/as well as WildFly/as well as the WildFly/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +There are different ways to use the https://quay.io/repository/wildfly/wildfly?tab=info[quay.io/wildfly/wildfly] image to create an *application image* (that would contain both WildFly and your deplo
s/deploys/deploy

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +In this article, we will see that this architecture also benefits users that are not using S2I and wants to keep control of the creation of their application images.
s/users that/users who/g
s/wants to keep/want to keep/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +Let's resume what is needed to move from the vanilla Docker image to the new runtime image for WildFly:
s/resume/review

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +In our example, our `microprofile-config` quickstart requires MicroProfile to run. WildFly provides a convenient `microprofile-platform` that provision everything that is needed to run MicroProfile a
s/provision/provisions

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +In our example, our `microprofile-config` quickstart requires MicroProfile to run. WildFly provides a convenient `microprofile-platform` that provision everything that is needed to run MicroProfile a
s/with only/to only/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +The `wildfly-maven-plugin` also provides the ability to execute JBoss CLI commands when WildFly is provisioned. This allows to substantially modify the standalone configuration to better fit the appl
s/allows to/allows you to/g

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +The most important feature pack is WildFly's own feature pack: `org.wildfly:wildfly-galleon-pack:26.1.1.Final` to contols the installation of WildFly itself.
s/controls/control

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +* The https://github.com/wildfly-extras/wildfly-cloud-galleon-pack[wildfly-cloud-galleon-pack] provides a set of additional features allowing you to configure a WildFly server to work on the cloud. I
s/route/routes
s/healthiness/health

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +It builds on top of the experience we gained from the Bootable Jar and provide a compelling architecture to control the full runtime (WildFly + the application deployments) from the application's `po
s/provide/provides

2022-08-02 20:12 UTC, bstansberry commented on _posts/2022-08-05-wildfly-maven-docker.adoc
> +The full customization of WildFly (using feature packs, packaging scripts, etc.) is controlled by the developer so that the runtime fits the uer's application.
s/uer's/user's/g

2022-08-03 09:51 UTC, jmesnil commented
thanks @bstansberry!

I open this PR as draft as it was not ready for review and needed more editing. Your review confirmed that! :) 
If you are ok with the structure and content, I'll polish it a bit more and we should be good

2022-08-03 12:54 UTC, jmesnil commented
@bstansberry I've addressed all your requests and added https://github.com/wildfly/wildfly.org/compare/54c0b8fc25d9a443feb5e82f9b8ec33687c03acd..b3821e39ca55cd872c376702507249e81dd8d430
I think we can rationalise our effort around our images (Docker, S2I, maybe buildpacks in a future) and wants to start a conversation on wildfly-dev about that. I see this article as a way to aggregate feedbacks on this effort.

2022-08-04 13:48 UTC, bstansberry approved these changes

2022-08-04 13:49 UTC, merged