New multi-arch WildFly S2I images
wildfly/wildfly.org pull request #384
Opened 2022-12-05 11:08 UTC by jfdenise

2022-12-05 11:08 UTC, jfdenise commented
@bstansberry @jmesnil @jamezp blog post for multi-arch images. Thank-you.

2022-12-05 11:13 UTC, darranl commented
We have a couple of blog posts describing how naming conventions have changed - could these include a link to the instructions describing how to use these images in case these posts become the first place users find?

2022-12-05 12:57 UTC, jmesnil commented
+1, for the docker images, the container registry explains the naming convention: https://quay.io/repository/wildfly/wildfly?tab=info

We could do the same for the S2I builder and runtime images

2022-12-05 19:25 UTC, bstansberry requested changes

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +(as explained in https://www.wildfly.org/news/2022/11/10/wildfly-docker-temurin/[this] blog post).
This is just a personal opinion, others might disagree, but I found using the title of the post "Updates on WildFly Docker Images" more comfortable to read than 'this'. Perhaps even personalize with 'as explained in Jeff Mesnil's https://....[Updates on WildFly Docker Images] blog post.'

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +NOTE: The previous WildFly images are now deprecated and are no more updated.
s/no more/no longer/g

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +These images are now deprecated and no more updated.
s/no more/no longer/g

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +== Deprecated wildfly images
s/wildfly/WildFly

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +The following single-arch images are now deprecated and are no more updated:
s/no more/no longer/g

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +== New OpenShift Image streams
s/streams/Streams

2022-12-05 19:25 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +A new release of link:https://github.com/wildfly/wildfly-charts[Helm Chart for WildFly] will be released soon to use the new images.
s/of/of the/g

2022-12-05 19:27 UTC, bstansberry commented on _posts/2022-12-05-wildfly-s2i-images-rename-multi-archs.adoc
> +== Deprecated snapshot multi-arch images
Snapshot
Multi-arch
Images

2022-12-07 13:05 UTC, jfdenise commented
@jmesnil @bstansberry @darranl , thank-you I have incorporated your feedback. I took the opportunity of the new Helm Charts release to advertise it.

2022-12-12 04:17 UTC, merged