Draft verbiage for central security policy
wildfly/wildfly.org pull request #393
Opened 2022-12-19 13:05 UTC by kabir

2022-12-19 13:29 UTC, fl4via commented
@kabir I liked the idea! IMHO, it would be great to add as well something mentioning that the person needs to be careful to not submit PRs with the fix or reproducer, or even keep the reproducer/fix in a public repo, everything should be private at the moment of notification... something along these lines.

2022-12-19 14:22 UTC, kabir commented
@fl4via I added another paragraph at the end

2022-12-19 14:48 UTC, bstansberry commented on _layouts/security.html
> +    </div>
I'm doubtful as to whether we should have this section. The simple policy a bunch of projects added only recommends email reporting, as does https://quarkus.io/security/ and https://www.keycloak.org/security.html.

If someone reads this and has two options it greatly increases the chances of them doing it wrong. If someone doesn't read this, it doesn't matter what it says. :)

2022-12-19 14:51 UTC, bstansberry commented on _layouts/security.html
> +</div>
I like what https://www.keycloak.org/security.html does about this, if we can work that out. It's simplest -- send us your info, we then get back to you on how to work the issue privately.

2022-12-19 15:03 UTC, kabir commented on _layouts/security.html
> +    </div>
@bstansberry I was in doubt whether to include this for the same reasons. I can remove it

2022-12-19 15:07 UTC, kabir commented on _layouts/security.html
> +</div>
@bstansberry updated

2022-12-19 19:37 UTC, bstansberry commented on _layouts/security.html
> +            Note that we will only fix such issues in the most recent major release of Wild<strong>Fly</strong>.</p>
I think "major" should be minor; e.g. we would not have fixed 26.0 once 26.1 was out.

2023-06-14 19:29 UTC, bstansberry requested changes

2023-06-14 19:29 UTC, bstansberry commented on _layouts/security.html
> +            issue is known internally until it public knowledge.
s/it public/it is public/g

2023-06-14 19:29 UTC, bstansberry commented on _layouts/security.html
> +            Our preferred way of reporting security issues in Wild<strong>Fly</strong> and its related projects are listed below.
s/are listed/is listed/g

2023-06-14 19:29 UTC, bstansberry commented on _layouts/security.html
> +            publicly. If you discover any publicly disclosed security vulnerabilities, please notify us immediately through
s/publicly./publicly, including in your own publicly visible git repository./g

2023-06-14 19:29 UTC, bstansberry commented on _layouts/security.html
> +        <p>The list at <a href="mailto:XXX@redhat.com">XXX@redhat.com</a> is the preferred mechanism for outside users
security@wildfly.org.  :)

2023-06-14 19:29 UTC, bstansberry commented on _layouts/security.html
> +            <a href="mailto:XXX@redhat.com">XXX@redhat.com</a>
security@wildfly.org.  :)

2023-06-15 15:20 UTC, bstansberry commented on _layouts/security.html
> +            publicly. If you discover any publicly disclosed security vulnerabilities, please notify us immediately through
@kabir This one is still outstanding.

2023-06-15 21:46 UTC, bstansberry approved these changes

2023-06-16 09:06 UTC, kabir commented
<img width="1077" alt="Screenshot 2023-06-16 at 11 04 59" src="https://github.com/wildfly/wildfly.org/assets/49927/73e6112d-07f2-4940-8795-259da77c2703">

<img width="963" alt="Screenshot 2023-06-16 at 11 06 10" 
src="https://github.com/wildfly/wildfly.org/assets/49927/07feb27f-39b4-483c-a139-88096e4c9090">

@bstansberry Screenshots of the rendered page (had to do two to get the full content)

2023-06-16 11:58 UTC, merged

2023-06-16 11:58 UTC, bstansberry commented
Thanks @kabir and @fl4via