Add a small tutorial to use Ansible to set up Wildfly
wildfly/wildfly.org pull request #394
Opened 2022-12-20 11:09 UTC by rpelisse

First time I'm blogging on the Wildfly website, so feel free to let me know what I did wrong :)

2023-01-09 11:26 UTC, rpelisse commented
@bstansberry Friendly reminder :)  (in case you're back from PTO today)

2023-01-09 11:29 UTC, darranl commented
FYI plenty of engineers can provide review, not necessarily Brian - if you can get some reviews in should be easier for one of the mergers to click merge.

2023-01-09 22:09 UTC, bstansberry requested changes
Thanks, Romain. I've made some copy-editing suggestions along with a rendering fix (repeated a lot.) Plus there are a couple missing example blocks.

Ping me on zulip when ready and I can turn it around pretty fast.

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
Duplicate; should be removed.

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +TODO
Interesting output! ;-)

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +Note that the playbook is not that long, but it does a lot for us. It performs almost 100 different tasks! Starting by automatically installs the dependencies, including the JVM required by Wildfly,
s/installs/installing

Either s/role sets does/role sets do/g or s/role sets/role set/g

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +The easiest way to confirm that the playbook did indeed install Wildfly and started three instances of the appserver is to use the systemctl command to check the associate services state:
The : implies there will be an example block.

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +=== Deploy an application to the JBoss EAP cluster
s/JBoss EAP/WildFly/g

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +Now, our three Wildfly are running, but the cluster has yet to form. Indeed, with no apps there is no reason for the cluster to exists. Let's modify our Ansible playbook to deploy a simple applicatio
s/exists/exist
s/instances,/instances;/g

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +=== Verify that Wildfly cluster is running  and the app is deployed
s/WildFly/the WildFly/g

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +---
4 dashes

2023-01-09 22:09 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +Here you go, with a short and simple playbook, we have fully automated the deployment of a Wildfly cluster! This playbook can now be used against one, two, three remote machine or even hundreds of th
s/Wildfly/WildFly

2023-01-10 15:24 UTC, bstansberry requested changes
Thanks @rpelisse!

There's one item still to update, and I noticed a different minor thing. The blog renders fine now though. :)

Also, please rename the file to 20230-01-10-ansible-wildfly.adoc. The file name doesn't really affect how it appears on the site or the URL, but having the names match or close to the URL is helpful for maintenance, finding content to steal from later, etc.

2023-01-10 15:24 UTC, bstansberry commented on _posts/2022-12-21-ansible-wildly.adoc
> +…
Nit: there are two ... lines here.

2023-01-10 16:06 UTC, bstansberry approved these changes

2023-01-10 16:06 UTC, merged