Added blog about grpc subsystem
wildfly/wildfly.org pull request #418
Opened 2023-05-22 21:30 UTC by ronsigal

2023-05-22 21:31 UTC, ronsigal commented
@hpehl, this is us!!

2023-05-23 06:29 UTC, hpehl requested changes
The content is great. Thanks for writing this. It's just the syntax highlighting that needs to be fixed.

2023-05-23 06:29 UTC, hpehl commented on _posts/2023-05-22-grpc-subsystem.adoc
> +[source,bash]
Hey, @ronsigal, the code syntax seems to be `[source,bash]` for all code samples.

2023-05-23 07:09 UTC, asoldano approved these changes

2023-05-23 09:49 UTC, ronsigal commented
Ahhhh, I used pandoc to convert it from markdown. :)

On Tue, May 23, 2023, 3:09 AM Alessio Soldano ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly.org/pull/418#pullrequestreview-1438813694>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEDP45FV5YKPEH3KPGGRN3XHRPC5ANCNFSM6AAAAAAYK7NW5U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-23 16:58 UTC, hpehl approved these changes

2023-05-23 16:59 UTC, ronsigal commented
Ok, I've changed most of the blocks to java. As I understand it, the source options depend on the syntax highlighter in use, and I found one that recognizes protobuf, though whatever Eclipse uses doesn't seem to recognize it. Also, there are a couple of blocks that don't really have a source type, so I just left them as "bash".

2023-05-28 23:44 UTC, jamezp approved these changes

2023-05-28 23:44 UTC, merged

2023-05-29 00:24 UTC, ronsigal commented
Thanks, @jamezp !

2023-05-29 15:47 UTC, ronsigal commented
Hey @hpehl, I see that the blog is published, but it doesn't have our names!!

2023-05-29 15:58 UTC, asoldano commented
@ronsigal I think your user is missing in https://github.com/wildfly/wildfly.org/blob/main/_data/authors.yaml . (Harald is there already, afaic instead)
In addition to that, I don't know if it's possible to have two names for a single blog post ...