Enhance and simplify logging guide
wildfly/wildfly.org pull request #541
Opened 2024-02-15 09:11 UTC by hpehl

Fixes #540

2024-02-15 09:13 UTC, hpehl commented
@jamezp, any objections to merging this?

2024-02-16 07:38 UTC, asoldano approved these changes

2024-02-16 16:03 UTC, jamezp requested changes
I actually see other things I'd like to change in here :) Would you prefer I make a PR to update this in general?

2024-02-16 16:03 UTC, jamezp commented on guides/application-logging.adoc
> +        log.trace("called method with: {}", name);
This isn't quite correct. For a format like this it needs to be `tracev`. However, I'd suggest using:
```java
log.tracef("called method: %s", name);
```

2024-02-16 17:14 UTC, jamezp commented
> @jamezp I agree it's better you open a separate PR to adjust the content.

Let me know what you think about #542 @hpehl. The plugin configuration could remove. However, it won't work out of the box the way that is currently shown. We might need a more uniform approach in general to that part of the message though.

2024-02-28 23:43 UTC, bstansberry commented
I've put the 'hold' label on this due to the discussion around #542. The label is just to make the fact there's an ongoing 'blocking' discussion more visible when looking at the PR queue.

2024-03-19 15:06 UTC, hpehl commented
@jamezp, I think we can close this PR now that https://github.com/wildfly/wildfly.org/pull/542 has been merged.

2024-03-19 20:47 UTC, closed without merging