How to Connect with the WildFly Community
wildfly/wildfly.org pull request #618
Opened 2024-05-30 14:14 UTC by RanabirChakraborty

Issue: https://github.com/wildfly/wildfly.org/issues/502

2024-05-30 14:14 UTC, RanabirChakraborty commented
@fjuma @bstansberry please review the article.

2024-05-30 15:54 UTC, bstansberry requested changes
Thanks Ranabir. I've made some comments.

WDYT about adding a quick section about RSS? It's kind of old school but we publish a feed at https://www.wildfly.org/feed.xml that's updated whenever anything is  published under wildfly.org/news.

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +WildFly is an open-source, production-ready, flexible and lightweight application server, offers all the necessary features to run and deploy Java applications. Connecting with the WildFly community
s/offers/offering

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +Participate in the https://groups.google.com/g/wildfly[WildFly Google Group] to ask questions, share knowledge, and engage with other users and developers. The forum is a valuable platform for seekin
s/discussion.You/discussions. You/g

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +Stay informed and connected by following WildFly on social media platforms. Follow us on https://x.com/WildFlyAS[X] and https://fosstodon.org/@wildflyas[Mastodon] for quick updates, announcements, an
s/and and/and

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +=== Submit Code or contribute to Documentation
s/contribute/Contribute

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +WildFly uses JIRA for issue tracking. You can find the list of issues and tasks on the https://issues.redhat.com/projects/WFLY/issues[WildFly JIRA dashboard]. If you've made improvements or fixed bug
s/visit WildFly/visit the WildFly/g

2024-05-30 15:54 UTC, bstansberry commented on _posts/2024-05-31-How-to-connect-with-WildFly-community.adoc
> +Participate in the https://groups.google.com/g/wildfly[WildFly Google Group] to ask questions, share knowledge, and engage with other users and developers. The forum is a valuable platform for seekin
I suggest adding something like:

"For discussions about using WildFly, try the https://wildfly.zulipchat.com/#narrow/stream/196266-wildfly-user[wildfly-user stream] in the chatroom.

2024-05-31 10:26 UTC, RanabirChakraborty commented
Thanks @bstansberry I have modified the article accordingly. Please review once.

2024-05-31 20:30 UTC, merged

2024-05-31 20:30 UTC, bstansberry commented
Thanks @RanabirChakraborty!