Add an article on how to use Ansible and the Yaml Config to automate Wildfly's subsystems config.
wildfly/wildfly.org pull request #633
Opened 2024-07-23 12:45 UTC by rpelisse

@bstansberry Let me know what you think about this proposal!

2024-08-05 06:14 UTC, rpelisse commented
@bstansberry Any chance to get this article approved and release soon? Anything I can change to make it better?

2024-08-22 20:07 UTC, bstansberry requested changes
@rpelisse This is good stuff. Once published WDYT about converting this to guides for https://www.wildfly.org/guides/?

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +* No matter what, remember the https://en.wikipedia.org/wiki/KISS_principle[KISS principe (Keep It Stupid Simple)].
s/principe/principle

You're nice; for us mean unprofessional people it's "Keep It Simple, Stupid!"  Your way is better for this kind of article. :)

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +Let's run again the `playbook`. As in the above example run, Ansible will notice the changed to the Yaml configuration file and consequently update the target's subsystems configuration, before resta
s/changed/change

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +The deployment of JDBC drivers and datasources on the target system is a somewhat more elaborated use case than the one we just saw with the messaging subsystem. Indeed, to add a JDBC driver to a Wil
s/created,/created;/g

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +Fortunately, here again, the Ansible collection for WildFly does most of the heavy lifting. In fact, the default `playbook` we used already comes with the setup of two JDCB drivers:
s/JDCB/JDBC

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +As shown above, the collection provides a generic role that takes care of creating the file hierarchy associated to a JDBC driver, but also download the required artifacts (jar file) along with gener
s/download/downloading

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +*Note:* _The Ansible collection for WildFly comes with a default template to generate the `module.xml` of a custom module. Obviously, this template might not be a good fit for ALL the drivers that us
s/user/users
s/providing/provided

2024-08-22 20:07 UTC, bstansberry commented on _posts/2024-07-10-ansible-yaml-wildfly.adoc
> +If this role ensures the modules are ready to be utilized, it does not, however, activate them. To make them available to use for datasources, we will add their definition to our Yaml configuration f
s/If this/While this/g

2024-09-09 11:04 UTC, rpelisse commented
@bstansberry Sorry for the delay, I have been on sick leave for the past weeks.

I've added all your fixes (check the new commit if you want to double check). Assuming it's good for you, I can squash the 4 commits into one and we can (hopefully) release this tomorrow? (I've updated the date accordingly).

Regarding the guide, why not? I can certainly took a look at updating the existing one with some of this content.

2024-09-10 14:57 UTC, bstansberry approved these changes

2024-09-10 14:57 UTC, merged

2024-09-10 14:57 UTC, bstansberry commented
Thanks @rpelisse! Very nice article!