New "Docker and kubernetes" category in Guides
wildfly/wildfly.org pull request #676
Opened 2024-10-25 14:06 UTC by tommaso-borgato

This PR moves the "WildFly mini Series" index up one level into the "Guides" page by creating a new "Docker and kubernetes"

2024-10-25 15:08 UTC, jmesnil requested changes

2024-10-25 15:13 UTC, tommaso-borgato commented on _data/guides.yaml
> +  - category: Docker and Kubernetes
That was somewhat intentional: the assumption is that the audience knows what Docker is but might be confused by the term "container" alone .... the guides actually use Podman and specify that Docker might e used as well as an alternative

2024-11-05 13:58 UTC, rjanik114 commented on _data/guides.yaml
> +  - category: Docker and Kubernetes
Just to bump this discussion forward - @jmesnil do you still stand by your comment?

2024-11-07 10:53 UTC, rhusar requested changes
As said on the chat, please don't call this Docker. It's a private closed-source company with proprietary software. Use 'Containers' when speaking generally.

2024-11-28 08:34 UTC, tommaso-borgato commented on _data/guides.yaml
> +  - category: Docker and Kubernetes
@jmesnil changed to "Podman/Docker and Kubernetes" ... I've seen this around ... 

![image](https://github.com/user-attachments/assets/6d7928a9-89fb-48a7-9201-c7385cf012ca)

2024-11-28 08:35 UTC, tommaso-borgato commented
> As said on the chat, please don't call this Docker. It's a private closed-source company with proprietary software. Use 'Containers' when speaking generally.

@rhusar what about https://github.com/wildfly/wildfly.org/pull/676#discussion_r1861731429 ?

2025-01-02 17:33 UTC, bstansberry commented
This will conflict with #712 and will need to be updated to put the new category in the correct alphabetical position.

2025-02-13 08:18 UTC, tommaso-borgato commented on _includes/index-guides.html
> +        {% else %}
@bstansberry Thank you

2025-03-10 08:17 UTC, tommaso-borgato commented
@bstansberry I have just re-based ans resolved conflicts: do you think we can merge this one now?

2025-03-10 14:32 UTC, yersan commented
Just wanted to add that at the OKR3 meeting, we distilled this category, among others, as "Cloud/Containerization". The full document with the categories we got is here: https://docs.google.com/document/d/1JoxoqN9Z5adpdNkTrWPdjLN3BroB4cBmV2ABYs-lm2I/edit?tab=t.0

It was just the point of view of the people who have been participating in the OKR3, it doesn't mean this PR should not be merged as it is because of that. In any case, as commented on https://github.com/wildfly/wildfly.org/pull/676#pullrequestreview-2420620815, the "docker" word for a category, I would say it is better not to use it at all.

2025-03-11 08:18 UTC, tommaso-borgato commented
> Cloud/Containerization

Thank you @yersan : I changed the name and here is how it would look now:
![image](https://github.com/user-attachments/assets/fd4e358b-5358-417a-8a15-35da9ae79080)

2025-03-11 09:00 UTC, rhusar requested changes

2025-03-11 09:00 UTC, rhusar commented on guides/get-started-microservices-on-kubernetes/simple-microservice-client-part2.adoc
> +NOTE: You can use link:https://docs.wildfly.org/wildfly-maven-plugin/releases/{version-wildfly-maven-plugin-docs}/image-mojo.html[`wildfly-maven-plugin`, window="_blank"] to automate the image push t
This appears duplicated?

2025-03-11 09:03 UTC, tommaso-borgato commented on guides/get-started-microservices-on-kubernetes/simple-microservice-client-part2.adoc
> +NOTE: You can use link:https://docs.wildfly.org/wildfly-maven-plugin/releases/{version-wildfly-maven-plugin-docs}/image-mojo.html[`wildfly-maven-plugin`, window="_blank"] to automate the image push t
> This appears duplicated?

Thank you @rhusar ! Fixed

2025-03-11 11:11 UTC, tommaso-borgato commented on _data/guides.yaml
> +      - title: Jakarta REST service using a Message Broker
Thank you @yersan ! Fixed

2025-03-11 11:11 UTC, tommaso-borgato commented on _data/guides.yaml
> +      - title: Jakarta REST service using Infinispan
Thank you @yersan ! Fixed

2025-03-11 11:13 UTC, tommaso-borgato commented on _data/guides.yaml
> +        description: Learn how to write JUnit 5 tests using Arquillian for Jakarta EE based applications.
Thank you @yersan ! rebase done

2025-03-11 11:26 UTC, yersan approved these changes
LGTM

2025-03-11 12:04 UTC, rhusar commented on _data/guides.yaml
> +    cat-id: docker-kubernetes
Can we get rid of `docker` also from the category id?

2025-03-11 13:13 UTC, tommaso-borgato commented on _data/guides.yaml
> +    cat-id: docker-kubernetes
@rhusar Tnks, changed

2025-03-13 01:33 UTC, bstansberry commented on _data/guides.yaml
> +  - category: Cloud / Containerization
Please put this block after Automation.

It's moved beyond any kind of 'Getting Started', so it should be alphabetical with the other categories.

Other than that, LGTM.

2025-03-13 07:52 UTC, tommaso-borgato commented on _data/guides.yaml
> +  - category: Cloud / Containerization
@bstansberry done!

2025-03-13 09:23 UTC, rhusar requested changes
Last suggestion - added liquid format fixes.

2025-03-13 09:23 UTC, rhusar commented on _includes/index-guides.html
> +                        <div class="description"><a href="{{site.baseurl}}{{ guide.url }}">{{ guide.description}}</a></div>
```suggestion
                        <div class="description"><a href="{{ site.baseurl }}{{ guide.url }}">{{ guide.description }}</a></div>
```

2025-03-13 09:23 UTC, rhusar commented on _includes/index-guides.html
> +                  <h4><a href="{{site.baseurl}}{{ guide.url }}">{{ guide.title}}</a></h4>
```suggestion
                  <h4><a href="{{ site.baseurl }}{{ guide.url }}">{{ guide.title }}</a></h4>
```

2025-03-13 12:52 UTC, rjanik114 approved these changes
LGTM.

2025-03-13 15:33 UTC, bstansberry approved these changes

2025-03-13 15:33 UTC, merged

2025-03-13 15:33 UTC, bstansberry commented
Thanks @tommaso-borgato @yersan @rhusar @jmesnil