Add a post about the vertx subsystem in WildFly Preview
wildfly/wildfly.org pull request #706
Opened 2024-12-16 11:48 UTC by gaol

The vertx subsystem has been integrated to WildFly Preview, it would be good to mention it here as well.

2024-12-16 12:38 UTC, kabir requested changes
A small nitpick from my side :-)

2024-12-16 12:38 UTC, kabir commented on _posts/2024-12-16-vertx-subsystem-in-preview.adoc
> +Currently, Vertx instances have been used by `opentelemetry` and `reactive-messaging` subsystems within WildFly to provide features powered by vertx components underneath, but there was no central me
The full name of the subsystem is actually 'microprofile-reactive-messaging-smallrye'

2024-12-16 13:31 UTC, gaol commented
@kabir thanks for the review. updated to the full subsystem name :)

2024-12-17 22:07 UTC, merged

2024-12-17 22:08 UTC, bstansberry commented
Thanks @gaol and @kabir